#!/usr/bin/env bash

ln -s -f ../JudoKit_iOS.h JudoKit_iOS.h
ln -s -f ../Models/CardDetails/JPCardNetworkType.h JPCardNetworkType.h
ln -s -f ../Models/ApplePayWrappers/JPApplePayWrappers.h JPApplePayWrappers.h
ln -s -f ../Models/CardDetails/JPCardDetails.h JPCardDetails.h
ln -s -f ../Models/Transaction/JPTransactionMode.h JPTransactionMode.h
ln -s -f ../Models/SDKInfo/JPSDKInfo.h JPSDKInfo.h
ln -s -f ../Models/Transaction/JPTransactionType.h JPTransactionType.h
ln -s -f ../Models/ClientDetails/JPClientDetails.h JPClientDetails.h
ln -s -f ../Models/CardPattern/JPCardPattern.h JPCardPattern.h
ln -s -f ../Models/Error/JPError.h JPError.h
ln -s -f ../Models/Amount/JPAmount.h JPAmount.h
ln -s -f ../Models/Configuration/JPConfiguration.h JPConfiguration.h
ln -s -f ../Models/ContactInformation/JPContactInformation.h JPContactInformation.h
ln -s -f ../Models/CardPattern/JPCardPatternType.h JPCardPatternType.h
ln -s -f ../Models/TransactionEnricher/JPRequestEnricher.h JPRequestEnricher.h
ln -s -f ../Models/PBBAConfiguration/JPPBBAConfiguration.h JPPBBAConfiguration.h
ln -s -f ../Models/CardStorage/JPCardStorage.h JPCardStorage.h
ln -s -f ../Models/IDEALBank/JPIDEALBank.h JPIDEALBank.h
ln -s -f ../Services/3DSService/JP3DSService.h JP3DSService.h
ln -s -f ../Models/ConsumerDevice/JPConsumerDevice.h JPConsumerDevice.h
ln -s -f ../Services/ApplePay/JPApplePayController.h JPApplePayController.h
ln -s -f ../Models/DictionaryConvertible/JPDictionaryConvertible.h JPDictionaryConvertible.h
ln -s -f ../Models/Section/JPSection.h JPSection.h
ln -s -f ../Models/Consumer/JPConsumer.h JPConsumer.h
ln -s -f ../Models/Theme/JPTheme.h JPTheme.h
ln -s -f ../Models/Constants/JPConstants.h JPConstants.h
ln -s -f ../Models/Authorization/Basic/JPBasicAuthorization.h JPBasicAuthorization.h
ln -s -f ../Models/EnchancedPaymentDetail/JPEnhancedPaymentDetail.h JPEnhancedPaymentDetail.h
ln -s -f ../Models/Address/JPAddress.h JPAddress.h
ln -s -f ../Models/Browser/JPBrowser.h JPBrowser.h
ln -s -f ../View/PBBAButton/JPPBBAButton.h JPPBBAButton.h
ln -s -f ../Models/Theme/JPThemable.h JPThemable.h
ln -s -f ../Models/UIConfiguration/JPUIConfiguration.h JPUIConfiguration.h
ln -s -f ../Models/Country/JPCountry.h JPCountry.h
ln -s -f ../Models/PaymentMethod/JPPaymentMethodType.h JPPaymentMethodType.h
ln -s -f ../Models/Reference/JPReference.h JPReference.h
ln -s -f ../Models/Authorization/Session/JPSessionAuthorization.h JPSessionAuthorization.h
ln -s -f ../Models/Reachability/JPReachability.h JPReachability.h
ln -s -f ../Models/ThreeDSecure/JPThreeDSecure.h JPThreeDSecure.h
ln -s -f ../Services/ApplePay/JPApplePayTypedefs.h JPApplePayTypedefs.h
ln -s -f ../Extensions/UIColor/UIColor+Additions.h UIColor+Additions.h
ln -s -f ../Models/StoredCardDetails/JPStoredCardDetails.h JPStoredCardDetails.h
ln -s -f ../Models/CardDetails/JPCardExpirationStatus.h JPCardExpirationStatus.h
ln -s -f ../Models/3DSConfiguration/JP3DSConfiguration.h JP3DSConfiguration.h
ln -s -f ../Models/Authorization/JPAuthorization.h JPAuthorization.h
ln -s -f ../Models/Response/JPResponse.h JPResponse.h
ln -s -f ../Models/ApplePayWrappers/JPApplePayTypes.h JPApplePayTypes.h
ln -s -f ../Models/ValidationResult/JPValidationResult.h JPValidationResult.h
ln -s -f ../Models/OrderDetails/JPOrderDetails.h JPOrderDetails.h
ln -s -f ../Models/PaymentShippingMethod/JPPaymentShippingMethod.h JPPaymentShippingMethod.h
ln -s -f ../Extensions/JPError/JPError+Additions.h JPError+Additions.h
ln -s -f ../Models/PaymentMethods/JPPaymentMethods.h JPPaymentMethods.h
ln -s -f ../Models/CardNetwork/JPCardNetwork.h JPCardNetwork.h
ln -s -f ../Extensions/UIFont/UIFont+Additions.h UIFont+Additions.h
ln -s -f ../Models/PaymentSummaryItem/JPPaymentSummaryItem.h JPPaymentSummaryItem.h
ln -s -f ../Models/Transaction/JPTransactionResult.h JPTransactionResult.h
ln -s -f ../Models/PrimaryAccountDetails/JPPrimaryAccountDetails.h JPPrimaryAccountDetails.h
ln -s -f ../Models/ApplePayConfiguration/JPApplePayConfiguration.h JPApplePayConfiguration.h
ln -s -f ../Models/BillingCountry/JPBillingCountry.h JPBillingCountry.h
ln -s -f ../Typedefs.h Typedefs.h
ln -s -f ../Models/PaymentMethod/JPPaymentMethod.h JPPaymentMethod.h
ln -s -f ../JudoKit.h JudoKit.h
ln -s -f ../Models/PostalAddress/JPPostalAddress.h JPPostalAddress.h
ln -s -f ../Models/Card/JPCard.h JPCard.h
ln -s -f ../Services/ApiService/JPApiService.h JPApiService.h
ln -s -f ../Services/ApiService/Session/JPSession.h JPSession.h
ln -s -f ../Models/Request/JPRequest.h JPRequest.h
ln -s -f ../Models/Request/JPBankOrderSaleRequest.h JPBankOrderSaleRequest.h
ln -s -f ../Models/Request/JPPaymentRequest.h JPPaymentRequest.h
ln -s -f ../Models/Request/JPTokenRequest.h JPTokenRequest.h
ln -s -f ../Models/Request/JPRegisterCardRequest.h JPRegisterCardRequest.h
ln -s -f ../Models/Request/JPSaveCardRequest.h JPSaveCardRequest.h
ln -s -f ../Models/Request/JPCheckCardRequest.h JPCheckCardRequest.h
ln -s -f ../Models/Request/JPApplePayRequest.h JPApplePayRequest.h
ln -s -f ../Models/Request/JP3DSecureAuthenticationResult.h JP3DSecureAuthenticationResult.h
ln -s -f ../View/LoadingButton/JPLoadingButton.h JPLoadingButton.h
