#!/usr/bin/env bash

# public headers
ln -s -f ../JudoKit_iOS.h JudoKit_iOS.h
ln -s -f ../Models/CardDetails/JPCardNetworkType.h JPCardNetworkType.h
ln -s -f ../Models/ApplePayWrappers/JPApplePayWrappers.h JPApplePayWrappers.h
ln -s -f ../Models/CardDetails/JPCardDetails.h JPCardDetails.h
ln -s -f ../Models/Transaction/JPTransactionMode.h JPTransactionMode.h
ln -s -f ../View/LoadingButton/JPLoadingButton.h JPLoadingButton.h
ln -s -f ../Models/SDKInfo/JPSDKInfo.h JPSDKInfo.h
ln -s -f ../Models/Transaction/JPTransactionType.h JPTransactionType.h
ln -s -f ../Models/ClientDetails/JPClientDetails.h JPClientDetails.h
ln -s -f ../Models/CardPattern/JPCardPattern.h JPCardPattern.h
ln -s -f ../Models/Error/JPError.h JPError.h
ln -s -f ../Models/Amount/JPAmount.h JPAmount.h
ln -s -f ../Models/Configuration/JPConfiguration.h JPConfiguration.h
ln -s -f ../Models/ContactInformation/JPContactInformation.h JPContactInformation.h
ln -s -f ../Models/CardPattern/JPCardPatternType.h JPCardPatternType.h
ln -s -f ../Models/TransactionEnricher/JPRequestEnricher.h JPRequestEnricher.h
ln -s -f ../Models/CardStorage/JPCardStorage.h JPCardStorage.h
ln -s -f ../Services/CardTransactionService/JPCardTransactionService.h JPCardTransactionService.h
ln -s -f ../Models/ConsumerDevice/JPConsumerDevice.h JPConsumerDevice.h
ln -s -f ../Services/ApplePay/JPApplePayController.h JPApplePayController.h
ln -s -f ../Models/DictionaryConvertible/JPDictionaryConvertible.h JPDictionaryConvertible.h
ln -s -f ../Models/Section/JPSection.h JPSection.h
ln -s -f ../Models/CardTransactionDetails/JPCardTransactionDetails.h JPCardTransactionDetails.h
ln -s -f ../Models/Consumer/JPConsumer.h JPConsumer.h
ln -s -f ../Models/Theme/JPTheme.h JPTheme.h
ln -s -f ../Models/Constants/JPConstants.h JPConstants.h
ln -s -f ../Models/Authorization/Basic/JPBasicAuthorization.h JPBasicAuthorization.h
ln -s -f ../Models/EnchancedPaymentDetail/JPEnhancedPaymentDetail.h JPEnhancedPaymentDetail.h
ln -s -f ../Models/Address/JPAddress.h JPAddress.h
ln -s -f ../Models/Browser/JPBrowser.h JPBrowser.h
ln -s -f ../Models/Theme/JPThemable.h JPThemable.h
ln -s -f ../Models/UIConfiguration/JPUIConfiguration.h JPUIConfiguration.h
ln -s -f ../Models/Country/JPCountry.h JPCountry.h
ln -s -f ../Models/AdministrativeDivision/JPAdministrativeDivision.h JPAdministrativeDivision.h
ln -s -f ../Models/PaymentMethod/JPPaymentMethodType.h JPPaymentMethodType.h
ln -s -f ../Models/Reference/JPReference.h JPReference.h
ln -s -f ../Models/Authorization/Session/JPSessionAuthorization.h JPSessionAuthorization.h
ln -s -f ../Extensions/NSString/NSString+Additions.h NSString+Additions.h
ln -s -f ../Models/Reachability/JPReachability.h JPReachability.h
ln -s -f ../Models/ThreeDSecure/JPThreeDSecure.h JPThreeDSecure.h
ln -s -f ../Services/ApplePay/JPApplePayTypedefs.h JPApplePayTypedefs.h
ln -s -f ../Extensions/UIColor/UIColor+Additions.h UIColor+Additions.h
ln -s -f ../Models/StoredCardDetails/JPStoredCardDetails.h JPStoredCardDetails.h
ln -s -f ../Models/CardDetails/JPCardExpirationStatus.h JPCardExpirationStatus.h
ln -s -f ../Models/3DSConfiguration/JP3DSConfiguration.h JP3DSConfiguration.h
ln -s -f ../Models/Authorization/JPAuthorization.h JPAuthorization.h
ln -s -f ../Models/Response/JPResponse.h JPResponse.h
ln -s -f ../Models/ApplePayWrappers/JPApplePayTypes.h JPApplePayTypes.h
ln -s -f ../Models/NetworkTimeout/JPNetworkTimeout.h JPNetworkTimeout.h
ln -s -f ../Models/ValidationResult/JPValidationResult.h JPValidationResult.h
ln -s -f ../Models/PaymentShippingMethod/JPPaymentShippingMethod.h JPPaymentShippingMethod.h
ln -s -f ../Models/Request/JPComplete3DS2Request.h JPComplete3DS2Request.h
ln -s -f ../Extensions/JPError/JPError+Additions.h JPError+Additions.h
ln -s -f ../Models/PaymentMethods/JPPaymentMethods.h JPPaymentMethods.h
ln -s -f ../Models/CardNetwork/JPCardNetwork.h JPCardNetwork.h
ln -s -f ../Extensions/UIFont/UIFont+Additions.h UIFont+Additions.h
ln -s -f ../Models/PaymentSummaryItem/JPPaymentSummaryItem.h JPPaymentSummaryItem.h
ln -s -f ../Extensions/NSBundle/NSBundle+Additions.h NSBundle+Additions.h
ln -s -f ../Models/Transaction/JPTransactionResult.h JPTransactionResult.h
ln -s -f ../Models/PrimaryAccountDetails/JPPrimaryAccountDetails.h JPPrimaryAccountDetails.h
ln -s -f ../Models/ApplePayConfiguration/JPApplePayConfiguration.h JPApplePayConfiguration.h
ln -s -f ../Models/ApplePayConfiguration/RecurringPaymentRequest/JPRecurringPaymentRequest.h JPRecurringPaymentRequest.h
ln -s -f ../Models/ApplePayConfiguration/RecurringPaymentSummaryItem/JPRecurringPaymentSummaryItem.h JPRecurringPaymentSummaryItem.h
ln -s -f ../Models/BillingCountry/JPBillingCountry.h JPBillingCountry.h
ln -s -f ../Typedefs.h Typedefs.h
ln -s -f ../Models/PaymentMethod/JPPaymentMethod.h JPPaymentMethod.h
ln -s -f ../JudoKit.h JudoKit.h
ln -s -f ../Models/PostalAddress/JPPostalAddress.h JPPostalAddress.h
ln -s -f ../Models/Card/JPCard.h JPCard.h
ln -s -f ../Services/ApiService/JPApiService.h JPApiService.h
ln -s -f ../Services/ApiService/Session/JPSession.h JPSession.h
ln -s -f ../Models/Request/JPRequest.h JPRequest.h
ln -s -f ../Models/Request/JPPreAuthRequest.h JPPreAuthRequest.h
ln -s -f ../Models/Request/JPPreAuthTokenRequest.h JPPreAuthTokenRequest.h
ln -s -f ../Models/Request/JPPreAuthApplePayRequest.h JPPreAuthApplePayRequest.h
ln -s -f ../Models/Request/JPPaymentRequest.h JPPaymentRequest.h
ln -s -f ../Models/Request/JPTokenRequest.h JPTokenRequest.h
ln -s -f ../Models/Request/JPRegisterCardRequest.h JPRegisterCardRequest.h
ln -s -f ../Models/Request/JPSaveCardRequest.h JPSaveCardRequest.h
ln -s -f ../Models/Request/JPCheckCardRequest.h JPCheckCardRequest.h
ln -s -f ../Models/Request/JPApplePayRequest.h JPApplePayRequest.h
ln -s -f ../Models/Request/JP3DSecureAuthenticationResult.h JP3DSecureAuthenticationResult.h
ln -s -f ../Models/RecommendationConfiguration/JPRecommendationConfiguration.h JPRecommendationConfiguration.h
ln -s -f ../Models/SubProductInfo/JPSubProductInfo.h JPSubProductInfo.h

# project headers
ln -s -f ../View/SectionView/JPSectionViewDelegate.h JPSectionViewDelegate.h
ln -s -f ../Modules/PaymentMethods/Interactor/JPPaymentMethodsInteractor.h JPPaymentMethodsInteractor.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/Cells/CardListFooterCell/JPPaymentMethodsCardListFooterCell.h JPPaymentMethodsCardListFooterCell.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/Cells/CardListHeaderCell/JPPaymentMethodsCardListHeaderCell.h JPPaymentMethodsCardListHeaderCell.h
ln -s -f ../Extensions/UIViewController/UIViewController+Additions.h UIViewController+Additions.h
ln -s -f ../Modules/Transaction/Interactor/JPTransactionInteractor.h JPTransactionInteractor.h
ln -s -f ../Modules/CardCustomization/Presenter/JPCardCustomizationPresenter.h JPCardCustomizationPresenter.h
ln -s -f ../Extensions/UIApplication/UIApplication+Additions.h UIApplication+Additions.h
ln -s -f ../Modules/Transaction/Builder/JPTransactionBuilder.h JPTransactionBuilder.h
ln -s -f ../Modules/PaymentMethods/View/JPPaymentMethodsViewController.h JPPaymentMethodsViewController.h
ln -s -f ../Modules/Transaction/Presenter/ViewModels/JPInputType.h JPInputType.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/Cells/PaymentMethodSelectionCell/JPPaymentMethodsSelectionCell.h JPPaymentMethodsSelectionCell.h
ln -s -f ../View/CardInputView/JPCardInputView.h JPCardInputView.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/Header/JPPaymentMethodsCardHeaderView.h JPPaymentMethodsCardHeaderView.h
ln -s -f ../Extensions/UIImage/UIImage+Additions.h UIImage+Additions.h
ln -s -f ../Modules/CardCustomization/View/Cells/CardCustomizationSubmitCell/JPCardCustomizationSubmitCellDelegate.h JPCardCustomizationSubmitCellDelegate.h
ln -s -f ../Helpers/JPFormatters/JPFormatters.h JPFormatters.h
ln -s -f ../View/RoundedCornerView/JPRoundedCornerView.h JPRoundedCornerView.h
ln -s -f ../Extensions/CLLocation/CLLocation+Additions.h CLLocation+Additions.h
ln -s -f ../Modules/CardScanController/JPCardScanControllerDelegate.h JPCardScanControllerDelegate.h
ln -s -f ../Extensions/JPResponse/JPResponse+Additions.h JPResponse+Additions.h
ln -s -f ../Modules/CardCustomization/View/Cells/CardCustomizationTitleCell/JPCardCustomizationTitleCell.h JPCardCustomizationTitleCell.h
ln -s -f ../Extensions/UITextField/UITextField+Additions.h UITextField+Additions.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/Header/JPPaymentMethodsEmptyHeaderView.h JPPaymentMethodsEmptyHeaderView.h
ln -s -f ../Extensions/NSArray/NSArray+Additions.h NSArray+Additions.h
ln -s -f ../Services/CardValidation/JPCardValidationService.h JPCardValidationService.h
ln -s -f ../Modules/Transaction/Presenter/JPTransactionPresenter.h JPTransactionPresenter.h
ln -s -f ../Modules/CardCustomization/Presenter/JPCardCustomizationViewModel.h JPCardCustomizationViewModel.h
ln -s -f ../Modules/CardCustomization/View/Cells/CardCustomizationPatternPickerCell/JPCardCustomizationPatternCell.h JPCardCustomizationPatternCell.h
ln -s -f ../Modules/PaymentMethods/Presenter/JPPaymentMethodsPresenter.h JPPaymentMethodsPresenter.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/JPPaymentMethodsHeaderView.h JPPaymentMethodsHeaderView.h
ln -s -f ../Modules/CardCustomization/Interactor/JPCardCustomizationInteractor.h JPCardCustomizationInteractor.h
ln -s -f ../Modules/Transaction/Presenter/ViewModels/JPTransactionViewModel.h JPTransactionViewModel.h
ln -s -f ../Modules/PaymentMethods/Router/JPPaymentMethodsRouter.h JPPaymentMethodsRouter.h
ln -s -f ../Services/Keychain/JPKeychainService.h JPKeychainService.h
ln -s -f ../Services/ApplePay/JPApplePayService.h JPApplePayService.h
ln -s -f ../View/LoadingView/JPLoadingView.h JPLoadingView.h
ln -s -f ../Modules/CardCustomization/View/Cells/CardCustomizationPatternPickerCell/JPCardCustomizationPatternPickerCell.h JPCardCustomizationPatternPickerCell.h
ln -s -f ../View/FloatingTextField/JPFloatingTextField.h JPFloatingTextField.h
ln -s -f ../View/CardInputView/Subviews/JPTransactionButton.h JPTransactionButton.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/Cells/CardListHeaderCell/JPPaymentMethodsCardListHeaderCellDelegate.h JPPaymentMethodsCardListHeaderCellDelegate.h
ln -s -f ../Modules/CardScanController/View/JPCardScanPreviewLayer.h JPCardScanPreviewLayer.h
ln -s -f ../Extensions/NSLayoutConstraint/NSLayoutConstraint+Additions.h NSLayoutConstraint+Additions.h
ln -s -f ../Modules/PaymentMethods/View/JPPaymentMethodsView.h JPPaymentMethodsView.h
ln -s -f ../Modules/CardCustomization/View/Cells/CardCustomizationSubmitCell/JPCardCustomizationSubmitCell.h JPCardCustomizationSubmitCell.h
ln -s -f ../View/InputField/JPInputField.h JPInputField.h
ln -s -f ../Extensions/UIStackView/UIStackView+Additions.h UIStackView+Additions.h
ln -s -f ../Models/ThreeDSecureTwo/JPThreeDSecureTwo.h JPThreeDSecureTwo.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/Cells/JPPaymentMethodConfigurable.h JPPaymentMethodConfigurable.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/CardView/JPOtherPaymentMethodView.h JPOtherPaymentMethodView.h
ln -s -f ../Modules/CardCustomization/View/Cells/CardCustomizationPatternPickerCell/JPCardCustomizationPatternPickerCellDelegate.h JPCardCustomizationPatternPickerCellDelegate.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/Cells/EmptyCardListCell/JPPaymentMethodsEmptyCardListCell.h JPPaymentMethodsEmptyCardListCell.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/CardView/JPCardView.h JPCardView.h
ln -s -f ../Helpers/Functions.h Functions.h
ln -s -f ../Modules/PaymentMethods/Builder/JPPaymentMethodsBuilder.h JPPaymentMethodsBuilder.h
ln -s -f ../Transitions/JPSliderTransitioningDelegate.h JPSliderTransitioningDelegate.h
ln -s -f ../Modules/Transaction/Router/JPTransactionRouter.h JPTransactionRouter.h
ln -s -f ../View/ApplePayButton/JPApplePayButton.h JPApplePayButton.h
ln -s -f ../Services/ConfigurationValidation/JPConfigurationValidationService.h JPConfigurationValidationService.h
ln -s -f ../View/CardInputView/Subviews/JPCardInputField.h JPCardInputField.h
ln -s -f ../View/SectionView/JPSectionView.h JPSectionView.h
ln -s -f ../Modules/CardScanController/JPCardScanController.h JPCardScanController.h
ln -s -f ../Modules/Transaction/View/JPTransactionViewController.h JPTransactionViewController.h
ln -s -f ../Modules/CardCustomization/Builder/JPCardCustomizationBuilder.h JPCardCustomizationBuilder.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/CardView/JPCardPaymentMethodView.h JPCardPaymentMethodView.h
ln -s -f ../Modules/CardCustomization/View/Cells/CardCustomizationTextInputCell/JPCardCustomizationTextInputCell.h JPCardCustomizationTextInputCell.h
ln -s -f ../Extensions/JPCardTransactionDetails/JPCardTransactionDetails+Additions.h JPCardTransactionDetails+Additions.h
ln -s -f ../Modules/PaymentMethods/Presenter/JPPaymentMethodsViewModel.h JPPaymentMethodsViewModel.h
ln -s -f ../Modules/CardCustomization/View/JPCardCustomizationViewController.h JPCardCustomizationViewController.h
ln -s -f ../Modules/CardCustomization/View/Cells/JPCardCustomizable.h JPCardCustomizable.h
ln -s -f ../Transitions/JPSliderPresentationController.h JPSliderPresentationController.h
ln -s -f ../Extensions/JPRequest/JPRequest+Additions.h JPRequest+Additions.h
ln -s -f ../Modules/CardCustomization/View/Cells/CardCustomizationHeaderCell/JPCardCustomizationHeaderCell.h JPCardCustomizationHeaderCell.h
ln -s -f ../Extensions/UIView/UIView+Additions.h UIView+Additions.h
ln -s -f ../Modules/CardCustomization/View/JPCardCustomizationView.h JPCardCustomizationView.h
ln -s -f ../Modules/CardScanController/View/JPCardScanView.h JPCardScanView.h
ln -s -f ../Modules/CardCustomization/Router/JPCardCustomizationRouter.h JPCardCustomizationRouter.h
ln -s -f ../Modules/CardCustomization/View/Cells/CardCustomizationIsDefaultCell/JPCardCustomizationIsDefaultCell.h JPCardCustomizationIsDefaultCell.h
ln -s -f ../Modules/PaymentMethods/View/Subviews/Cells/CardCell/JPPaymentMethodsCardCell.h JPPaymentMethodsCardCell.h
ln -s -f ../View/CardInputView/Subviews/JPCardNumberField.h JPCardNumberField.h
ln -s -f ../Extensions/NSObject/NSObject+Additions.h NSObject+Additions.h
ln -s -f ../View/InputField/JPInputFieldDelegate.h JPInputFieldDelegate.h
ln -s -f ../Models/SessionConfiguration/JPSessionConfiguration.h JPSessionConfiguration.h
ln -s -f ../Extensions/NSNumberFormatter/NSNumberFormatter+Additions.h NSNumberFormatter+Additions.h
ln -s -f ../Models/CReqParameters/JPCReqParameters.h JPCReqParameters.h
ln -s -f ../Models/NetworkTimeout/JPNetworkTimeout.h JPNetworkTimeout.h
ln -s -f ../Extensions/NSNumber/NSNumber+Additions.h NSNumber+Additions.h
ln -s -f ../View/CardInputView/Subviews/JPTransactionScanCardButton.h JPTransactionScanCardButton.h
ln -s -f ../View/CardInputView/Subviews/JPSecurityMessageView.h JPSecurityMessageView.h
ln -s -f ../View/CardInputView/Subviews/JPSecurityMessageView.h JPSecurityMessageView.h
ln -s -f ../View/CardInputView/Subviews/JPPhoneCodeInputField.h JPPhoneCodeInputField.h
ln -s -f ../View/CardInputView/Subviews/JPIntrinsicSizeAwareScrollView.h JPIntrinsicSizeAwareScrollView.h
ln -s -f ../View/CardInputView/Subviews/JPForm.h JPForm.h
ln -s -f ../View/CardInputView/Subviews/JPCardDetailsForm.h JPCardDetailsForm.h
ln -s -f ../View/CardInputView/Subviews/JPBillingInformationForm.h JPBillingInformationForm.h
ln -s -f ../View/CardInputView/Subviews/ActionBar/JPActionBarDelegate.h JPActionBarDelegate.h
ln -s -f ../View/CardInputView/Subviews/ActionBar/JPActionBar.h JPActionBar.h
ln -s -f ../Modules/Transaction/Presenter/ViewModels/JPPresentationMode.h JPPresentationMode.h
ln -s -f ../Extensions/JPConfiguration/JPConfiguration+Additions.h JPConfiguration+Additions.h
ln -s -f ../Services/RecommendationService/JPRecommendationService.h JPRecommendationService.h
ln -s -f ../Services/ConfigurationValidation/JPConfigurationValidationService.h JPConfigurationValidationService.h
ln -s -f ../Services/CardTransactionService/JPCardTransactionType.h JPCardTransactionType.h
ln -s -f ../Models/Response/Recommendation/TransactionOptimisation/JPTransactionOptimisation.h JPTransactionOptimisation.h
ln -s -f ../Models/Response/Recommendation/TransactionOptimisation/JPRecommendationOptimisationThreeDSChallengePreference.h JPRecommendationOptimisationThreeDSChallengePreference.h
ln -s -f ../Models/Response/Recommendation/TransactionOptimisation/JPRecommendationOptimisationExemption.h JPRecommendationOptimisationExemption.h
ln -s -f ../Models/Response/Recommendation/RecommendationData/JPRecommendationData.h JPRecommendationData.h
ln -s -f ../Models/Response/Recommendation/RecommendationData/JPRecommendationAction.h JPRecommendationAction.h
ln -s -f ../Models/Response/Recommendation/JPRecommendationResponse.h JPRecommendationResponse.h
ln -s -f ../Models/Request/Recommendation/RecommendationPaymentMethod/JPRecommendationPaymentMethod.h JPRecommendationPaymentMethod.h
ln -s -f ../Models/Request/Recommendation/PaymentMethodCipher/JPPaymentMethodCipher.h JPPaymentMethodCipher.h
ln -s -f ../Models/Request/Recommendation/JPRecommendationRequest.h JPRecommendationRequest.h
ln -s -f ../Models/CardTransactionDetailsOverrides/JPCardTransactionDetailsOverrides.h JPCardTransactionDetailsOverrides.h
