version: 2.1

executors:
  macos:
    macos:
      xcode: 11.3.0

jobs:
  carthage_update_sdk:
    executor: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-ios-carthage-{{ checksum "Cartfile" }}
            - judokit-ios-carthagekit-{{ checksum "Cartfile" }}
            - judokit-ios-carthagecache-{{ checksum "Cartfile" }}
      - run:
          name: Carthage Update
          command: carthage update
      - save_cache:
          key: judokit-ios-carthage-{{ checksum "Cartfile" }}
          paths:
            - Carthage
      - save_cache:
          key: judokit-ios-carthagekit-{{ checksum "Cartfile" }}
          paths:
            - ~/Library/Caches/org.carthage.CarthageKit
      - save_cache:
          key: judokit-ios-carthagecache-{{ checksum "Cartfile" }}
          paths:
            - ~/Library/Caches/carthage
  bundle_install:
    executor: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-ios-{{ checksum "Gemfile" }}
      - run:
          name: Bundle Install
          command: bundle install
      - save_cache:
          key: judokit-ios-{{ checksum "Gemfile" }}
          paths: ~/.bundle/cache
  carthage_update_sample:
    executor: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-sample-carthage-{{ checksum "Examples/CarthageExampleApp/Cartfile" }}
            - judokit-sample-carthagekit-{{ checksum "Examples/CarthageExampleApp/Cartfile" }}
            - judokit-sample-carthagecache-{{ checksum "Examples/CarthageExampleApp/Cartfile" }}
      - run:
          name: Carthage Update Sample App
          working_directory: Examples/CarthageExampleApp
          command: carthage update
      - save_cache:
          key: judokit-sample-carthage-{{ checksum "Examples/CarthageExampleApp/Cartfile" }}
          paths:
            - Examples/CarthageExampleApp/Carthage
      - save_cache:
          key: judokit-sample-carthagekit-{{ checksum "Examples/CarthageExampleApp/Cartfile" }}
          paths:
            - ~/Library/Caches/org.carthage.CarthageKit
      - save_cache:
          key: judokit-sample-carthagecache-{{ checksum "Examples/CarthageExampleApp/Cartfile" }}
          paths:
            - ~/Library/Caches/carthage
  pod_install_objc_sample:
    executor: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-sample-objc-pod-{{ checksum "Examples/ObjectiveCExampleApp/Podfile" }}
      - run:
          name: Pod Install ObjC Sample App
          working_directory: Examples/ObjectiveCExampleApp
          command: pod install
      - save_cache:
          key: judokit-sample-objc-pod-{{ checksum "Examples/ObjectiveCExampleApp/Podfile" }}
          paths:
            - Examples/ObjectiveCExampleApp/Pods
  pod_install_swift_sample:
    executor: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-sample-swift-pod-{{ checksum "Examples/SwiftExampleApp/Podfile" }}
      - run:
          name: Pod Install Swift Sample App
          working_directory: Examples/SwiftExampleApp
          command: pod install
      - save_cache:
          key: judokit-sample-swift-pod-{{ checksum "Examples/SwiftExampleApp/Podfile" }}
          paths:
            - Examples/SwiftExampleApp/Pods
  build_sdk:
    executor: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-ios-carthage-{{ checksum "Cartfile" }}
      - run:
          name: Build SDK
          command: |
            xcodebuild clean build \
              -project JudoKit_iOS.xcodeproj \
              -scheme JudoKit_iOS \
              -configuration Release \
              -sdk iphonesimulator \
              -derivedDataPath DerivedData
      - persist_to_workspace:
          root: .
          paths:
            - DerivedData
  build_carthage_sample:
    executor: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-sample-carthage-{{ checksum "Examples/CarthageExampleApp/Cartfile" }}
      - run:
          name: Build Carthage Sample
          command: |
            xcodebuild clean build \
              -project Examples/CarthageExampleApp/CarthageExampleApp.xcodeproj \
              -scheme CarthageExampleApp \
              -configuration Release \
              -sdk iphonesimulator \
              -derivedDataPath Examples/CarthageExampleApp/DerivedData
  build_objc_sample:
    executor: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-sample-objc-pod-{{ checksum "Examples/ObjectiveCExampleApp/Podfile" }}
      - run:
          name: Build ObjC Sample
          command: |
            xcodebuild clean build \
              -project Examples/ObjectiveCExampleApp/ObjectiveCExampleApp.xcodeproj \
              -scheme ObjectiveCExampleApp \
              -configuration Release \
              -sdk iphonesimulator \
              -derivedDataPath Examples/ObjectiveCExampleApp/DerivedData
  build_swift_sample:
    executor: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-sample-swift-pod-{{ checksum "Examples/SwiftExampleApp/Podfile" }}
      - run:
          name: Build Swift Sample
          command: |
            xcodebuild clean build \
              -project Examples/SwiftExampleApp/SwiftExampleApp.xcodeproj \
              -scheme SwiftExampleApp \
              -configuration Release \
              -sdk iphonesimulator \
              -derivedDataPath Examples/SwiftExampleApp/DerivedData
  unit_test_sdk:
    executor: macos
    steps:
      - checkout
      - restore_cache:
          keys:
            - judokit-ios-carthage-{{ checksum "Cartfile" }}
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Sonar Build Wrapper
          command: |
            curl -o /var/tmp/build-wrapper-macosx-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-macosx-x86.zip
            unzip /var/tmp/build-wrapper-macosx-x86.zip -d /var/tmp
            sudo mkdir -p /opt/build-wrapper-macosx/bin
            sudo mv /var/tmp/build-wrapper-macosx-x86/* /opt/build-wrapper-macosx/bin/
            rm -rf /var/tmp/build-wrapper-macosx-x86
            ln -s /opt/build-wrapper-macosx/bin/build-wrapper-macosx-x86 /usr/local/bin/build-wrapper-macosx-x86
      - run:
          name: Run SDK Unit Tests
          command: |
            build-wrapper-macosx-x86 --out-dir build-wrapper-output xcodebuild \
              -project JudoKit_iOS.xcodeproj \
              -scheme JudoKit_iOS \
              -destination 'platform=iOS Simulator,name=iPhone 11' \
              -derivedDataPath DerivedData \
              test
      - run:
          name: Covert XCode Coverage Reports to SonarQube Format
          command: |
            curl -o xccov-to-sonarqube-generic.sh https://raw.githubusercontent.com/SonarSource/sonar-scanning-examples/master/swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh
            chmod +x xccov-to-sonarqube-generic.sh
            ./xccov-to-sonarqube-generic.sh DerivedData/Logs/Test/*.xcresult/ > build-wrapper-output/sonarqube-generic-coverage.xml
            rm xccov-to-sonarqube-generic.sh
      - persist_to_workspace:
          root: .
          paths:
            - DerivedData
            - build-wrapper-output
  validate_podspec:
    executor: macos
    steps:
      - checkout
      - run:
          name: Validate PodSpec
          command: pod lib lint --no-subspecs --allow-warnings

  # unit_test_sample:

  # instrumented_test_sample:

  sonar_scan:
    executor: macos
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Sonar Scanner
          command: |
            export SONARSCANNER_VERSION=4.3.0.2102
            curl -o sonarscanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONARSCANNER_VERSION}-macosx.zip
            sudo unzip -q sonarscanner.zip -d /opt
            rm sonarscanner.zip
            ln -s /opt/sonar-scanner-${SONARSCANNER_VERSION}-macosx/bin/sonar-scanner /usr/local/bin/sonar-scanner
      - run:
          name: Run Sonar Scan
          command: |
            export REPO_OWNER=Judopay
            export REPO_NAME=$(basename `git config --get remote.origin.url` .git)
            export GENERIC_COVERAGE_REPORTS=$(find `pwd -P` -name sonarqube-generic-coverage.xml)
            export OBJC_BUILD_WRAPPER_OUTPUT_DIR=$(dirname $(find `pwd -P` -name build-wrapper-dump.json))
            export BRANCH_NAME=$(git branch | grep \* | cut -d ' ' -f2)
            PARAMS=(-Dsonar.host.url=https://sonarcloud.io)
            PARAMS+=(-Dsonar.login=$SONARCLOUD_TOKEN)
            PARAMS+=(-Dsonar.organization=judopay)
            PARAMS+=(-Dsonar.projectKey=${REPO_OWNER}_${REPO_NAME})
            PARAMS+=(-Dsonar.projectName=${REPO_NAME})
            PARAMS+=(-Dsonar.sources=.)
            PARAMS+=(-Dsonar.coverageReportPaths=${GENERIC_COVERAGE_REPORTS})
            PARAMS+=(-Dsonar.cfamily.build-wrapper-output=${OBJC_BUILD_WRAPPER_OUTPUT_DIR})
            PARAMS+=(-Dsonar.cfamily.cache.enabled=false)
            PARAMS+=(-Dproject.settings=.sonarscan)
            if [ "$BRANCH_NAME" == "master" ]; then
              echo "On master branch. Running default scan."
            elif PR_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls | jq ".[] | select(.head.ref == \"$BRANCH_NAME\")"); then
              PR_NUMBER=$(echo "$PR_INFO" | jq -r '.number')
              PR_TARGET=$(echo "$PR_INFO" | jq -r '.base.ref')
              if [ "$PR_NUMBER" != "" ]; then
                echo "Pull request $PR_NUMBER found. Running a pull request scan."
                PARAMS+=(-Dsonar.pullrequest.github.repository=${REPO_OWNER}/${REPO_NAME})
                PARAMS+=(-Dsonar.pullrequest.base=$PR_TARGET)
                PARAMS+=(-Dsonar.pullrequest.key=$PR_NUMBER)
                PARAMS+=(-Dsonar.pullrequest.branch=$BRANCH_NAME)
                PARAMS+=(-Dsonar.pullrequest.provider=GitHub)
              fi
            else
              echo "Couldnt find pull request. Running short-lived branch scan."
              PARAMS+=(-Dsonar.branch.name=$BRANCH_NAME)
              PARAMS+=(-Dsonar.branch.target=master)
            fi
            sonar-scanner "${PARAMS[@]}"
  release_sample:
    executor: macos
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Firebase CLI
          command: curl -sL https://firebase.tools | bash
      - run:
          name: Store Google Service Account
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Create Release Notes
          command: echo "$(git log -1 --pretty=format:"%b")" > ./notes.txt
      - run:
          name: Distribute Sample App
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
            firebase appdistribution:distribute \
              somepackage \
              --app "$IOS_FIREBASE_APP_ID" \
              --groups "default-testers" \
              --release-notes-file ./notes.txt
  release_sdk:
    executor: macos
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Release SDK to CocoaPods
          command: pod trunk push JudoKit-iOS.podspec --allow-warnings

workflows:
  version: 2
  build:
    jobs:
      - carthage_update_sdk
      - bundle_install
      - carthage_update_sample
      - pod_install_objc_sample
      - pod_install_swift_sample
      - build_sdk:
          requires:
            - carthage_update_sdk
          filters:
            tags:
              only:
                - /^v((\d)+\.){1,2}(\d+)/i
      - build_carthage_sample:
          requires:
            - carthage_update_sample
          filters:
            tags:
              only:
                - /^v((\d)+\.){1,2}(\d+)/i
      - build_objc_sample:
          requires:
            - pod_install_objc_sample
          filters:
            tags:
              only:
                - /^v((\d)+\.){1,2}(\d+)/i
      - build_swift_sample:
          requires:
            - pod_install_swift_sample
          filters:
            tags:
              only:
                - /^v((\d)+\.){1,2}(\d+)/i
      - unit_test_sdk:
          requires:
            - build_sdk
      - validate_podspec
      - sonar_scan:
          context: shared-secrets
          requires:
            - unit_test_sdk
      - release_sample:
          context: shared-secrets
          requires:
            - unit_test_sdk
            - validate_podspec
            - build_objc_sample
          filters:
            branches:
              only:
                - master
      - release_sdk:
          context: shared-secrets
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^v((\d)+\.){1,2}(\d+)/i
