platform :ios, '11.0'

target 'ObjectiveCExampleApp' do
  use_frameworks!

  # Pods for ObjectiveCExampleApp
  pod 'JudoKit-iOS', :path => '../../'

  pod 'InAppSettingsKit', '3.3.3'
  pod 'CocoaDebug'

  target 'ObjectiveCExampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObjectiveCExampleAppUITests' do
    # Pods for testing
    pod 'Cucumberish', :git => 'https://github.com/mpetrenco/Cucumberish.git'
  end

end
