platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

target 'ObjectiveCExampleApp' do
  pod 'JudoKit-iOS', :path => '../../'

  pod 'InAppSettingsKit', '3.3.3'
  pod 'CocoaDebug'

  target 'ObjectiveCExampleAppTests' do
    inherit! :search_paths
  end

  target 'ObjectiveCExampleAppUITests' do
    pod 'Cucumberish', :git => 'https://github.com/mpetrenco/Cucumberish.git'
  end
end
