default_platform(:ios)

platform :ios do
  before_all do
    en_ci_utils_init
  end
  
  lane :generate_code_quality_reports do
    sh("cd .. && ./clang-format.sh lint") # check code format
    scan(use_clang_report_name: true)     # run tests and generate reports
    oclint(report_type: 'html')           # run static code analyzer
    slather                               # generate code coverage reports
  end

end