name: iOS Build and Test Sample Apps

on:
  pull_request:
  workflow_dispatch:
jobs:
  build_and_test_sample_apps:
    uses: Judopay/github-actions/.github/workflows/ios-build-and-test.yml@chore/NONE/updates-xcode-version
    secrets: inherit
