name: iOS Test Sample Apps with Firebase

on:
  pull_request:

jobs:
  build_sample_apps:
    uses: Judopay/github-actions/.github/workflows/ios-build-and-test-sample-apps.yml@master
    secrets: inherit
  test_sampple_apps:
    uses: Judopay/github-actions/.github/workflows/ios-test-sample-apps-firebase.yml@master
    secrets: inherit
