# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'SwiftExampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftExampleApp
  pod 'JudoKitObjC', :path => '../../'

  pod 'InAppSettingsKit'
  pod 'CocoaDebug'

  target 'SwiftExampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftExampleAppUITests' do
    # Pods for testing
  end

end
